AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-api-example
  
  Sample SAM Template for serverless-api-example


Resources:
  BaristaTeamTable:
    Type: AWS::Serverless::SimpleTable

  Greeter:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: greeter/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64

  HelloWorldGraphQLApi:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      SchemaUri: ./gql/schema.graphql
      Auth:
        Type: API_KEY
      ApiKeys:
        MyApiKey:
          Description: my api key
      DataSources:
        DynamoDb:
          BaristaTeams:
            TableName: !Ref BaristaTeamTable
            TableArn: !GetAtt BaristaTeamTable.Arn
        Lambda:
          Greeter:
            FunctionArn: !GetAtt Greeter.Arn
      Functions:
        preprocessBaristaTeamItem:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: NONE
          CodeUri: ./gql/preprocessBaristaTeamItem.js
        createBaristaTeamItem:
          Runtime:
            Name: APPSYNC_JS
            Version: "1.0.0"
          DataSource: BaristaTeams
          CodeUri: ./gql/createBaristaTeamItem.js
        getBaristaTeamFromTable:
          Runtime:
            Name: APPSYNC_JS
            Version: "1.0.0"
          DataSource: BaristaTeams
          CodeUri: ./gql/getBaristaTeamFromTable.js
        greet:
          Runtime:
            Name: APPSYNC_JS
            Version: "1.0.0"
          DataSource: Greeter
          CodeUri: ./gql/greet.js
      Resolvers:
        Mutation:
          addBaristaTeamInstance:
            Runtime:
              Name: APPSYNC_JS
              Version: "1.0.0"
            Pipeline:
            - preprocessBaristaTeamItem
            - createBaristaTeamItem
        Query:
          getBaristaTeamInstance:
            Runtime:
              Name: APPSYNC_JS
              Version: "1.0.0"
            Pipeline:
            - getBaristaTeamFromTable

Outputs:
  HelloWorldGraphQLApi:
    Description: HelloWorldGraphQLApi endpoint URL for Prod environment
    Value: !GetAtt HelloWorldGraphQLApi.GraphQLUrl
  HelloWorldGraphQLApiMyApiKey:
    Description: API Key for HelloWorldGraphQLApi
    Value: !GetAtt HelloWorldGraphQLApiMyApiKey.ApiKey

